#!/usr/bin/env bash

BASEDIR=$(cd `dirname "$0"` && pwd)
YAMLFILE="${BASEDIR}/pacman.yaml"
REPO_DIR="${BASEDIR}/../../"
TEMPORARY_DIR="${BASEDIR}/.tmp/"

for codebase in $(yq eval -o=j $YAMLFILE | jq -cr '.[]'); do
    # download and extract each artifact asynchronously
    # the brackets create a subshell
    (   
        # extract name, artifactUrl, and artifactLevel from json into bash variables
        read -d ' ' name artifactUrl artifactLevel <<< $(jq -r '.name,.artifactUrl,.artifactLevel' <<< "$codebase")
        temporaryFile="${TEMPORARY_DIR}${name}"
        temporaryExtraction="${TEMPORARY_DIR}${name}-extracted"

        echo "Downloading and extracting '${name}' from '${artifactUrl}' to '${temporaryExtraction}'";
        wget --quiet "$artifactUrl" -O "${temporaryFile}"
        rm -rf ${temporaryExtraction}
        mkdir -p ${temporaryExtraction}
        bsdtar --strip-components=${artifactLevel} -xf "${temporaryFile}" -C "${temporaryExtraction}"
    ) &
done

# wait for the artifcats to download and extract 
wait

for codebase in $(yq eval -o=j $YAMLFILE | jq -cr '.[]'); do
    # extract name, and destination from json into bash variables
    read -d ' ' name destination <<< $(jq -r '.name,.destination' <<< "$codebase")
    temporaryExtraction="${TEMPORARY_DIR}${name}-extracted/."
    targetDestination="${REPO_DIR}${destination}"
    
    echo "Moving '${name}' from '${temporaryExtraction}' to '${targetDestination}'";
    cp -fa "${temporaryExtraction}" "${targetDestination}"
done
