#!/usr/bin/env sh
docker build --tag wbstack/mediawiki/pacman:0.0.1 --file ./wbstack/sync/pacman.Dockerfile ./wbstack/sync/
docker run --rm -u $(id -u ${USER}):$(id -g ${USER}) -v $PWD:/app --entrypoint bash wbstack/mediawiki/pacman:0.0.1 /app/wbstack/sync/pacman-script
