#!/usr/bin/env sh
docker build --tag wbstack/mediawiki/wikiman:0.0.1 --file ./wbstack/sync/wikiman.Dockerfile ./wbstack/sync/
docker run --rm -it -u $(id -u ${USER}):$(id -g ${USER}) -v $PWD:/app wbstack/mediawiki/wikiman:0.0.1 python /app/wbstack/sync/wikiman.py
