name: sync daily run

on:
  # Non hour start chosen deliberately https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#scheduled-events
  schedule:
    - cron: '6 12 * * *'
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/daily.sync.yml

jobs:
  sync_simple:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: run sync
        run: ./sync.sh
      - name: Show `git diff`` output
        run: git diff
      # Only fail in CI when there is diff content NOT on a pull request
      - name: Check only composer changed
        if: steps.diff.outcome  != 'success' && github.event_name != 'pull_request'
        run: |
          GIT_CHANGES=$(git status --porcelain=v1 -- ':!dist/vendor/composer' ':!dist/vendor/autoload.php')
          if [[ $GIT_CHANGES ]]; then
              exit 1
          fi
  sync_composer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
      - name: run sync
        run: ./sync.sh -u
      - name: Show `git diff`` output
        run: git diff
      # Only fail in CI when there is diff content NOT on a pull request
      - name: Check only composer changed
        if: steps.diff.outcome  != 'success' && github.event_name != 'pull_request'
        run: |
          GIT_CHANGES=$(git status --porcelain=v1 -- ':!dist/vendor/composer' ':!dist/vendor/autoload.php')
          if [[ $GIT_CHANGES ]]; then
              exit 1
          fi
