name: wbstack python lint

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Install pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Install wikiman requirements
        working-directory: ./sync/wikiman
        run: python -m pip install --no-cache-dir -r requirements.txt

      - name: Lint all python files
        run: find ./ -type f -name "*.py" -not -path "./dist/*" | xargs pylint
