name: wbstack sync

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: run sync
      run: ./wbstack/sync.sh
    - name: Check only composer autoloaders changed
      run: diff wbstack.sync.txt <(./wbstack/sync.sh)