name: wbstack sync

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: run sync
      run: ./sync.sh
    - name: Show `git diff`` output
      run: git diff
    - name: Check only composer autoloaders changed
      run: diff -Z ./.github/workflows/wbstack.sync.expect.txt <(git status --porcelain=v1)
