name: wbstack python lint

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install pylint
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Install sync Requirements
      working-directory: ./sync
      run: python -m pip install --no-cache-dir -r requirements.txt

    - name: Lint all python files
      run: find ./ -type f -name "*.py" -not -path "./dist/*" | xargs pylint
