name: wikiman

on:
  schedule:
    - cron:  '6 12 * * *'
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: copy pacman.yaml
      run: cp ./sync/pacman.yaml ./sync/current-pacman.yaml 
    - name: write GH action token to file
      run: echo ${{ secrets.GITHUB_TOKEN }} > ./sync/.github
    - name: run wikiman
      run: ./sync/wikiman
    - name: Show diff of current pacman.yaml
      run: diff ./sync/pacman.yaml ./sync/current-pacman.yaml
